#!/usr/bin/env bash
#Install ngix and have a file that returns the string "Hello World"  inside

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /etc/nginx/html;
	index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx start
